Syncing Tutorials with the SDK
OffchainLabs/arbitrum-tutorials pull request #83
Opened 2022-11-30 15:12 UTC by mahsamoosavi

The Greeter script is now using the estimateAll method from the SDK to get all the gas required params for the L1-L2 msg.

2022-11-30 17:26 UTC, gzeoneth requested changes
`estimateAll` accept an optional `gasOverrides`, can you include example as well?

2022-12-05 15:47 UTC, mahsamoosavi commented
> `estimateAll` accept an optional `gasOverrides`, can you include example as well?

Sure! Should we the gas overriding params as hardcoded?

2022-12-06 13:45 UTC, gzeoneth approved these changes
minor edit, lgtm

2022-12-06 13:45 UTC, gzeoneth commented on packages/greeter/scripts/exec.js
> +      percentIncrease: BigNumber.from(10), //how much to increase the base by
```suggestion
      base: undefined, // when defining as "undefined", the value will be estimated from rpc
      min: BigNumber.from(1000), // set a minimum gas limit, using 1000 as an example
      percentIncrease: BigNumber.from(10), // how much to increase the base for buffer
```

2022-12-06 14:25 UTC, merged